### ISSUE TITLE
直传JavaScript new Date() 对象的时间格式好像不支持时间戳格式的哦

### ISSUE THREAD

**Issue by mrjucn** [Tokinx/lately#1]
![image](https://user-images.githubusercontent.com/15878249/200871564-0cc65559-32d5-4804-90f8-6d30fbea033b.png)
![image](https://user-images.githubusercontent.com/15878249/200871659-6ea64d7d-10e2-4cb0-894a-c70983c8b438.png)

**Comment by mrjucn** [comment]
> new date输出的这个格式，lately js 没法解析额。

**Comment by mrjucn** [comment]
![image](https://user-images.githubusercontent.com/15878249/200872676-5579dab3-fdd6-46f9-8212-3d42bb27dfc5.png)
然后我自己时间戳转了一下，lately js才解析到位。。。给时间戳解析也干进去吧，这多好。嘿嘿。

**Comment by Tokinx** [comment]
<img width="393" alt="Snipaste_2022-11-10_11-45-35" src="https://user-images.githubusercontent.com/4526339/200995921-2dc1ab0f-ea72-4465-82f0-6fb52cba7fd4.png">

因为new Date不支持解析10位的时间戳呀，时间戳是13位的

**Comment by Tokinx** [comment]
> 

10位的时间戳是缩短的，严格意义上可能不算时间戳，new Date()也不能解析10位“时间戳”。
用的时候*1000还好吧，不是插件bug

**Comment by mrjucn** [comment]
> > 
> 
> 10位的时间戳是缩短的，严格意义上可能不算时间戳，new Date()也不能解析10位“时间戳”。 用的时候*1000还好吧，不是插件bug

额，没说这个是bug哈，只是觉得用的时候*1000，没法转化为几天前这种。依然还是“Sun Nov 13 2022 14:48:15 GMT+0800 (中国标准时间)”。这种没法格式化时间。。
